'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace DatabaseUserSettings


    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()> _
    Friend Class Localization

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")> _
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As New Global.System.Resources.ResourceManager("Localization", GetType(Localization).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(ByVal value As System.Globalization.CultureInfo)
                resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Cannot load user settings from the Model.xafml file.
        '''.
        ''' </summary>
        Friend Shared ReadOnly Property CannotLoadUserSettingsFromFile() As String
            Get
                Return ResourceManager.GetString("CannotLoadUserSettingsFromFile", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Cannot load user settings from the database.
        '''.
        ''' </summary>
        Friend Shared ReadOnly Property CannotLoadUserSettingsFromTheDatabase() As String
            Get
                Return ResourceManager.GetString("CannotLoadUserSettingsFromTheDatabase", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Cannot locate a target List View within a Detail View..
        ''' </summary>
        Friend Shared ReadOnly Property CannotLocateTargetsListView() As String
            Get
                Return ResourceManager.GetString("CannotLocateTargetsListView", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Cannot save user settings to the database.
        '''.
        ''' </summary>
        Friend Shared ReadOnly Property CannotSaveUserSettingsToTheDatabase() As String
            Get
                Return ResourceManager.GetString("CannotSaveUserSettingsToTheDatabase", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Default.
        ''' </summary>
        Friend Shared ReadOnly Property DefaultAspect() As String
            Get
                Return ResourceManager.GetString("DefaultAspect", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to Contact your application Administrator or Configurator for a solution. You can also try to find the reason of this failure yourself by checking the log file.
        '''.
        ''' </summary>
        Friend Shared ReadOnly Property UserSettingsFailureSuggestion() As String
            Get
                Return ResourceManager.GetString("UserSettingsFailureSuggestion", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
